// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYRZUz8MGM4YXdNrZC5kf2dIIHRWO07qI',
    appId: '1:759377123405:web:8adf7ed06680f81acfe404',
    messagingSenderId: '759377123405',
    projectId: 'flutterchatapp-5a082',
    authDomain: 'flutterchatapp-5a082.firebaseapp.com',
    storageBucket: 'flutterchatapp-5a082.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVjnABXKkgW1Jv9sS152GSl3JRty-mhn0',
    appId: '1:759377123405:android:f3ea7d3e55723f1dcfe404',
    messagingSenderId: '759377123405',
    projectId: 'flutterchatapp-5a082',
    storageBucket: 'flutterchatapp-5a082.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNMNLpovhRIOps28Z4GHynJOUgj259O0I',
    appId: '1:759377123405:ios:f489eac30c58507dcfe404',
    messagingSenderId: '759377123405',
    projectId: 'flutterchatapp-5a082',
    storageBucket: 'flutterchatapp-5a082.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNMNLpovhRIOps28Z4GHynJOUgj259O0I',
    appId: '1:759377123405:ios:f489eac30c58507dcfe404',
    messagingSenderId: '759377123405',
    projectId: 'flutterchatapp-5a082',
    storageBucket: 'flutterchatapp-5a082.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYRZUz8MGM4YXdNrZC5kf2dIIHRWO07qI',
    appId: '1:759377123405:web:7386171348d0ba29cfe404',
    messagingSenderId: '759377123405',
    projectId: 'flutterchatapp-5a082',
    authDomain: 'flutterchatapp-5a082.firebaseapp.com',
    storageBucket: 'flutterchatapp-5a082.firebasestorage.app',
  );
}
